import { execFile } from "node:child_process";
import { appendFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile);
const root = process.env.GITHUB_WORKSPACE || process.cwd();
const outDir = join(root, ".mcprigor", "action");
const reportPath = join(outDir, "report.md");
await mkdir(outDir, { recursive: true });

const suites = await expandPatterns((process.env.INPUT_SUITES || "tests/**/*.mcpr").split(/\r?\n/).map((x) => x.trim()).filter(Boolean));
const rows = [];
let failed = false;
for (const suite of suites) {
  const resultFile = join(outDir, safeName(suite) + ".json");
  const run = await rigor(["test", suite, "--json", resultFile, "--github-annotations"]);
  let parsed;
  try { parsed = JSON.parse(await readFile(resultFile, "utf8")); } catch {}
  const summary = parsed?.summary;
  rows.push({ suite, code: run.code, summary, durationMs: parsed?.durationMs, status: run.code === 0 ? "passed" : "failed", output: tail(run.output, 1200) });
  if (run.code !== 0) failed = true;
}
if (!suites.length) { failed = true; rows.push({ suite: "(no suites matched)", code: 2, status: "failed", output: "Check the action's suites input." }); }

let drift;
let driftPath = "";
if (process.env.INPUT_LOCK) {
  const suite = suites[0];
  if (!suite) drift = { code: 2, output: "No suite available for drift." };
  else drift = await rigor(["drift", suite, "--against", process.env.INPUT_LOCK, "--fail-on", process.env.INPUT_FAIL_ON || "breaking", "--markdown", "--github-annotations"]);
  if (drift.code !== 0) failed = true;
  driftPath = join(outDir, "drift.md");
  const driftBody = [
    "<!-- mcprigor-drift-report -->",
    "# MCP Rigor contract drift",
    "",
    `- Suite: \`${suites[0] || "(none)"}\``,
    `- Lock: \`${process.env.INPUT_LOCK}\``,
    `- Gate: \`${process.env.INPUT_FAIL_ON || "breaking"}\``,
    `- Result: ${drift.code === 0 ? "✅ within gate" : "❌ gate failed"}`,
    "",
    drift.output.trim() || (drift.code === 0 ? "No contract drift detected." : "Drift command failed."),
    "",
  ].join("\n");
  await writeFile(driftPath, driftBody, "utf8");
}

let flaky;
if ((process.env.INPUT_FLAKY || "true") === "true") {
  const history = join(root, ".mcprigor", "workspace-history.jsonl");
  try { await readFile(history); flaky = await rigor(["flaky", root]); } catch {}
}

const passedTests = rows.reduce((n, x) => n + (x.summary?.passed || 0), 0);
const failedTests = rows.reduce((n, x) => n + (x.summary?.failed || 0), 0);
const skippedTests = rows.reduce((n, x) => n + (x.summary?.skipped || 0), 0);
const icon = failed ? "❌" : "✅";
const body = [
  "<!-- mcprigor-action-report -->",
  `## ${icon} MCP Rigor`,
  "",
  `**${passedTests} passed · ${failedTests} failed · ${skippedTests} skipped** across ${suites.length} suite${suites.length === 1 ? "" : "s"}.`,
  "",
  "| Suite | Result | Passed | Failed | Skipped | Duration |",
  "|---|---:|---:|---:|---:|---:|",
  ...rows.map((x) => `| \`${escapePipe(x.suite)}\` | ${x.status === "passed" ? "✅ passed" : "❌ failed"} | ${x.summary?.passed ?? "—"} | ${x.summary?.failed ?? "—"} | ${x.summary?.skipped ?? "—"} | ${x.durationMs != null ? `${x.durationMs} ms` : "—"} |`),
  "",
  ...(drift ? ["### Contract drift", "", drift.output.trim() || (drift.code === 0 ? "No contract drift detected." : "Drift command failed."), ""] : []),
  ...(flaky ? ["### Flaky-test warning", "", "```text", tail(flaky.output, 2400), "```", ""] : []),
  ...rows.filter((x) => x.code !== 0).flatMap((x) => [`<details><summary>Failure: ${escapeHtml(x.suite)}</summary>`, "", "```text", x.output, "```", "", "</details>", ""]),
  `<sub>Generated by [MCP Rigor](https://mcprigor.com) · deterministic MCP testing · commit \`${(process.env.GITHUB_SHA || "local").slice(0, 12)}\`</sub>`,
  "",
].join("\n");
await writeFile(reportPath, body, "utf8");
await output("status", failed ? "failed" : "passed");
await output("report", reportPath);
await output("drift-report", driftPath);
await output("artifact-dir", outDir);
if (failed) process.exitCode = 1;

async function rigor(args) {
  try { const { stdout, stderr } = await exec(process.execPath, [join(root, "node_modules", "mcprigor", "dist", "cli.js"), ...args], { cwd: root, env: process.env, maxBuffer: 10 * 1024 * 1024 }); return { code: 0, output: stdout + stderr }; }
  catch (error) { return { code: Number(error.code) || 1, output: String(error.stdout || "") + String(error.stderr || error.message || "") }; }
}
async function expandPatterns(patterns) {
  const all = await walk(root, ""); const files = new Set();
  for (const pattern of patterns) {
    const regex = globRegex(pattern.replaceAll("\\\\", "/"));
    for (const file of all) if (regex.test(file)) files.add(file);
  }
  return [...files].sort();
}
async function walk(directory, prefix) {
  const out = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".git" || entry.name.startsWith(".")) continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...await walk(join(directory, entry.name), rel)); else out.push(rel);
  }
  return out;
}
function globRegex(pattern) {
  let source = "^";
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i];
    if (ch === "*" && pattern[i + 1] === "*" && pattern[i + 2] === "/") { source += "(?:.*/)?"; i += 2; }
    else if (ch === "*" && pattern[i + 1] === "*") { source += ".*"; i++; }
    else if (ch === "*") source += "[^/]*";
    else if (ch === "?") source += "[^/]";
    else source += ch.replace(/[\\^$+?.()|{}\[\]]/g, "\\$&");
  }
  return new RegExp(source + "$");
}
async function output(name, value) { if (process.env.GITHUB_OUTPUT) await appendFile(process.env.GITHUB_OUTPUT, `${name}=${value}\n`); else console.log(`${name}=${value}`); }
function safeName(x) { return x.replace(/[^a-z0-9._-]+/gi, "_"); }
function tail(x, n) { return String(x || "").slice(-n); }
function escapePipe(x) { return String(x).replaceAll("|", "\\|"); }
function escapeHtml(x) { return String(x).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); }
