import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { startWorkspace } from "../src/workspace.js";

const roots: string[] = []; afterEach(async () => Promise.all(roots.splice(0).map((path) => rm(path, { recursive: true, force: true }))));
async function fixture() { const root = await mkdtemp(join(tmpdir(), "rigor-web-")); roots.push(root); await writeFile(join(root, "suite.mcpr"), `Suite: "Workspace"\nServer: node missing.js\nTest: "ping"\n  Send "ping"\n`); return root; }
describe("QA workspace", () => {
  it("serves UI, lists suites, reads files, and validates", async () => { const root = await fixture(); const app = await startWorkspace({ root }); try { expect((await fetch(app.url)).status).toBe(200); const boot = await (await fetch(`${app.url}/api/v1/bootstrap`)).json() as any; expect(boot.capabilities).toContain("parity"); const list = await (await fetch(`${app.url}/api/v1/suites`)).json() as any; expect(list.suites[0].path).toBe("suite.mcpr"); const file = await (await fetch(`${app.url}/api/v1/file?path=suite.mcpr`)).json() as any; const validated = await fetch(`${app.url}/api/v1/validate`, { method: "POST", headers: { "content-type": "application/json", origin: app.url, "x-mcp-csrf": boot.csrf }, body: JSON.stringify({ path: "suite.mcpr" }) }); expect((await validated.json() as any).valid).toBe(true); expect(file.etag).toMatch(/^sha256:/); } finally { await app.close(); } });
  it("rejects traversal and unauthorized writes", async () => { const root = await fixture(); const app = await startWorkspace({ root }); try { expect((await fetch(`${app.url}/api/v1/file?path=../outside.mcpr`)).status).toBe(500); expect((await fetch(`${app.url}/api/v1/file`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ path: "suite.mcpr", text: "x" }) })).status).toBe(403); } finally { await app.close(); } });
  it("uses optimistic concurrency for saves", async () => { const root = await fixture(); const app = await startWorkspace({ root }); try { const boot = await (await fetch(`${app.url}/api/v1/bootstrap`)).json() as any; const headers = { "content-type": "application/json", origin: app.url, "x-mcp-csrf": boot.csrf }; const old = await (await fetch(`${app.url}/api/v1/file?path=suite.mcpr`)).json() as any; expect((await fetch(`${app.url}/api/v1/file`, { method: "PUT", headers, body: JSON.stringify({ path: "suite.mcpr", text: old.text + "# saved\n", etag: old.etag }) })).status).toBe(200); expect((await fetch(`${app.url}/api/v1/file`, { method: "PUT", headers, body: JSON.stringify({ path: "suite.mcpr", text: "stale", etag: old.etag }) })).status).toBe(412); } finally { await app.close(); } });
});
