export type FailureCategory = "configuration" | "language-compilation" | "data-loading" | "extension" | "server-spawn" | "initialization" | "transport" | "mcp-error" | "schema" | "assertion" | "timeout" | "cancellation" | "cleanup" | "internal";
export const FAILURE_CODES: Record<FailureCategory, string> = { configuration: "MCP-CONFIG-000", "language-compilation": "MCP-LANG-000", "data-loading": "MCP-DATA-000", extension: "MCP-EXT-000", "server-spawn": "MCP-SPAWN-000", initialization: "MCP-INIT-000", transport: "MCP-TRANSPORT-000", "mcp-error": "MCP-REMOTE-000", schema: "MCP-SCHEMA-000", assertion: "MCP-ASSERT-000", timeout: "MCP-TIMEOUT-000", cancellation: "MCP-CANCEL-000", cleanup: "MCP-CLEANUP-000", internal: "MCP-INTERNAL-000" };
const HELP: Record<FailureCategory, string> = { configuration: "Check the suite target and settings.", "language-compilation": "Check the highlighted plain-language statement.", "data-loading": "Check the data source, row, and column named above.", extension: "Review the extension manifest, permissions, and exported operation.", "server-spawn": "Check that the server command exists and starts from the configured directory.", initialization: "The server started but did not complete MCP initialization.", transport: "Check the process or HTTP connection and server logs.", "mcp-error": "The MCP server rejected this request; review its code and message.", schema: "The returned value does not match the required schema.", assertion: "Compare the expected value or path with the server response.", timeout: "The operation took too long; inspect the server or increase the explicit timeout.", cancellation: "The operation was cancelled before completion.", cleanup: "The test ran, but cleanup failed; inspect cleanup actions and server shutdown.", internal: "This is an unexpected MCP Rigor failure; retain sanitized evidence and report it." };
export class RigorError extends Error { constructor(public readonly category: FailureCategory, public readonly code: string, message: string, public readonly actionable = HELP[category], public readonly cause?: unknown) { super(`${code} ${message}`); this.name = "RigorError"; } }
export interface FailureInfo { category: FailureCategory; code: string; message: string; actionable: string }
export function classifyFailure(error: unknown, fallback: FailureCategory = "internal"): FailureInfo {
  const message = error instanceof Error ? error.message : String(error); const code = message.match(/\b(?:MCP|MCPLANG|QA)-(?:[A-Z]+-?)*\d{3}\b/)?.[0] ?? FAILURE_CODES[fallback]; const category = categoryFor(code, message, fallback); return { category, code, message: message.replace(new RegExp(`^${escape(code)}\\s*`), ""), actionable: HELP[category] };
}
export function formatFailure(error: unknown, fallback?: FailureCategory): string { const value = classifyFailure(error, fallback); return `${value.code} [${value.category}] ${sanitizeTerminal(value.message)}\nAction: ${value.actionable}`; }
export function sanitizeTerminal(value: string): string { return value.replace(/\u001b\][^\u0007]*(?:\u0007|\u001b\\)/g, "").replace(/\u001b\[[0-?]*[ -\/]*[@-~]/g, "").replace(/\u001b[P_^][\s\S]*?(?:\u001b\\|\u0007)/g, "").replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g, ""); }
function categoryFor(code: string, message: string, fallback: FailureCategory): FailureCategory { if (/CONFIG|STATE|REQ/.test(code)) return "configuration"; if (/LANG|FLOW/.test(code)) return "language-compilation"; if (/DATA/.test(code)) return "data-loading"; if (/EXT/.test(code)) return "extension"; if (/SPAWN|ENOENT/.test(code + message)) return "server-spawn"; if (/INIT|CONNECT/.test(code)) return "initialization"; if (/TRANSPORT|HTTP/.test(code)) return "transport"; if (/SCHEMA/.test(code)) return "schema"; if (/ASSERT|SNAPSHOT/.test(code)) return "assertion"; if (/TIMEOUT|Timed out|exceeded/i.test(code + message)) return "timeout"; if (/CANCEL|abort/i.test(code + message)) return "cancellation"; if (/CLEANUP/.test(code)) return "cleanup"; if (/REMOTE|MCP error/i.test(code + message)) return "mcp-error"; return fallback; }
function escape(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
