import { writeFile } from "node:fs/promises";
import type { RunResult } from "./types.js";
import { sanitizeTerminal } from "./errors.js";
import type { TimelineEntry } from "./timeline.js";

export function terminalReport(result: RunResult): string {
  const lines = [`\nMCP Rigor — ${result.suiteName}`];
  for (const test of result.tests) {
    const mark = test.status === "passed" ? "✓" : test.status === "skipped" ? "○" : test.status === "blocked" ? "⊘" : "✗";
    lines.push(`${mark} ${test.name} (${test.durationMs}ms)`);
    for (const step of test.steps) {
      lines.push(`  ${step.status === "passed" ? "✓" : "✗"} ${step.name} (${step.durationMs}ms)`);
      if (step.error) {
        lines.push(`    ${friendly(step.error)}`);
        lines.push("    Tip: check the expected value and the field name in this step.");
      }
    }
    if (test.error && !test.steps.some((step) => step.error === test.error)) lines.push(`  ${test.error}`);
  }
  lines.push(`\n${result.summary.passed} passed, ${result.summary.failed} failed, ${result.summary.skipped} skipped, ${result.summary.blocked} blocked (${result.durationMs}ms)`);
  return sanitizeTerminal(lines.join("\n"));
}

export async function writeJsonReport(result: RunResult, file: string): Promise<void> {
  await writeFile(file, `${JSON.stringify(result, null, 2)}\n`, "utf8");
}

export async function writeHtmlReport(result: RunResult, file: string, timeline?: TimelineEntry[]): Promise<void> {
  const tests = result.tests.map((test) => `<section class="test ${test.status}"><h2>${test.status === "passed" ? "✓" : test.status === "skipped" ? "○" : "✗"} ${xml(test.name)}</h2>${test.error ? `<p>${xml(friendly(test.error))}</p>` : ""}<ol>${test.steps.map((step) => `<li class="${step.status}"><strong>${xml(step.name)}</strong>${step.error ? `<p>${xml(friendly(step.error))}</p>` : ""}</li>`).join("")}</ol></section>`).join("");
  const timelineHtml = timeline && timeline.length ? renderTimeline(timeline) : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${xml(result.suiteName)} — MCP Rigor</title><style>body{font:16px system-ui;max-width:900px;margin:40px auto;padding:0 20px;color:#17202a}header{padding:24px;border-radius:14px;background:#f4f7fb}.summary{font-size:20px}.test{border:1px solid #ddd;border-left:6px solid #777;border-radius:10px;padding:12px 20px;margin:18px 0}.passed{border-color:#16803c}.failed{border-color:#c62828}.skipped{border-color:#a66b00}li{padding:6px}code{background:#eee;padding:2px 5px}footer{color:#667;margin-top:32px}h2.section{margin-top:36px}.tl{list-style:none;padding:0;margin:0;border:1px solid #e2e6ec;border-radius:10px;overflow:hidden}.tl>li{padding:0;border-top:1px solid #eef1f4}.tl>li:first-child{border-top:0}.tl-row{display:flex;gap:12px;align-items:center;padding:10px 16px;cursor:pointer;background:#fff}.tl-row:hover{background:#f7f9fc}.tl-seq{color:#8a94a6;font-variant-numeric:tabular-nums;min-width:2.4em}.tl-dot{width:10px;height:10px;border-radius:50%;background:#16803c;flex:0 0 auto}.tl-err .tl-dot{background:#c62828}.tl-meta .tl-dot{background:#8a94a6}.tl-label{flex:1;font-weight:600}.tl-method{color:#446;font-weight:400;font-size:14px}.tl-dur{color:#667;font-variant-numeric:tabular-nums;font-size:14px}.tl-body{display:none;padding:0 16px 14px;background:#fbfcfe}.tl-body.open{display:block}.tl-body h4{margin:12px 0 4px;color:#556;font-size:13px;text-transform:uppercase;letter-spacing:.04em}.tl-body pre{margin:0;background:#0f1720;color:#e6edf3;padding:12px;border-radius:8px;overflow:auto;font:13px ui-monospace,Menlo,monospace}.hint{color:#667;font-size:14px}</style></head><body><header><h1>${xml(result.suiteName)}</h1><p class="summary"><b>${result.summary.passed}</b> passed · <b>${result.summary.failed}</b> failed · <b>${result.summary.skipped}</b> skipped · <b>${result.summary.blocked}</b> blocked</p><p>${result.durationMs} ms · Evidence <code>${xml(result.evidenceHash.slice(0, 23))}…</code></p></header>${tests}${timelineHtml}<footer>Generated by MCP Rigor. Secrets were redacted before this report was created.</footer><script>document.querySelectorAll('.tl-row').forEach(function(row){row.addEventListener('click',function(){var b=row.nextElementSibling;if(b)b.classList.toggle('open');});});</script></body></html>`;
  await writeFile(file, html, "utf8");
}

function renderTimeline(timeline: TimelineEntry[]): string {
  const items = timeline.map((entry) => {
    const cls = entry.status === "error" ? "tl-err" : entry.kind === "call" ? "" : "tl-meta";
    const dur = entry.durationMs === undefined ? "" : `<span class="tl-dur">${entry.durationMs} ms</span>`;
    const method = entry.method && entry.method !== entry.label ? `<span class="tl-method">${xml(entry.method)}</span>` : "";
    const scope = [entry.testId, entry.step].filter(Boolean).map((value) => xml(String(value)));
    const body = [
      scope.length ? `<h4>Scope</h4><pre>${scope.join(" › ")}</pre>` : "",
      entry.request !== undefined ? `<h4>Request</h4><pre>${xml(entry.request)}</pre>` : "",
      entry.response !== undefined ? `<h4>Response</h4><pre>${xml(entry.response)}</pre>` : "",
    ].join("");
    return `<li class="${cls}"><div class="tl-row"><span class="tl-seq">${entry.sequence}</span><span class="tl-dot"></span><span class="tl-label">${xml(entry.label)} ${method}</span>${dur}</div><div class="tl-body">${body || "<p class=\"hint\">No captured payload for this event.</p>"}</div></li>`;
  }).join("");
  return `<h2 class="section">Session timeline</h2><p class="hint">Click any request to expand its captured request and response. Secrets are redacted.</p><ul class="tl">${items}</ul>`;
}


export function junitXml(result: RunResult): string {
  const cases = result.tests.map((test) => {
    const detail = test.status === "failed" ? `<failure message="${xml(test.error ?? "failed")}"/>` : test.status === "skipped" ? "<skipped/>" : "";
    return `  <testcase name="${xml(test.name)}" time="${(test.durationMs / 1000).toFixed(3)}">${detail}</testcase>`;
  });
  const output = [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    `<testsuite name="${xml(result.suiteName)}" tests="${result.tests.length}" failures="${result.summary.failed}" skipped="${result.summary.skipped}" time="${(result.durationMs / 1000).toFixed(3)}">`,
    ...cases,
    "</testsuite>",
    "",
  ].join("\n");
  return output;
}

function friendly(value: string): string {
  return value
    .replace(/^MCP-[A-Z]+-\d{3}\s*/, "")
    .replace(/^\$\.?/, "the result field ")
    .replace(/received/g, "but the server returned");
}

function xml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

/** GitHub Actions workflow commands: one error annotation per failed test, one notice for the summary. */
export function githubAnnotations(result: RunResult, file?: string): string {
  const esc = (value: string) => value.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
  const lines: string[] = [];
  for (const test of result.tests) {
    if (test.status !== "failed") continue;
    const location = file ? `file=${esc(file)},` : "";
    lines.push(`::error ${location}title=${esc(`MCP Rigor: ${test.name}`)}::${esc(test.error ?? "Test failed")}`);
  }
  const passed = result.tests.filter((t) => t.status === "passed").length;
  const failed = result.tests.filter((t) => t.status === "failed").length;
  lines.push(`::notice title=MCP Rigor::${passed} passed, ${failed} failed (${result.tests.length} total)`);
  return lines.join("\n");
}

export async function writeJunitReport(result: RunResult, file: string): Promise<void> {
  await writeFile(file, junitXml(result), "utf8");
}
